using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas.Parser;
using iText.Kernel.Pdf.Canvas.Parser.Listener;
using ReportBuilder.Models;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace ReportBuilder.Services;

public class PdfReportParser
{
    public MobileAppReportConfig ParseMobileAppReport(byte[] pdfBytes)
    {
        try
        {
            using var ms = new MemoryStream(pdfBytes);
            ms.Position = 0; // Ensure we're at the start

            var readerProperties = new iText.Kernel.Pdf.ReaderProperties();
            using var pdfReader = new PdfReader(ms, readerProperties);
            using var pdfDoc = new PdfDocument(pdfReader);

            // Extract text from all pages to find our JSON marker
            var fullText = string.Empty;
            for (int i = 1; i <= pdfDoc.GetNumberOfPages(); i++)
            {
                var page = pdfDoc.GetPage(i);
                var strategy = new SimpleTextExtractionStrategy();
                fullText += PdfTextExtractor.GetTextFromPage(page, strategy) + "\n";
            }

            // Look for our JSON marker: <!--REPORT_CONFIG_JSON:{...}-->
            var jsonMatch = Regex.Match(fullText, @"<!--REPORT_CONFIG_JSON:(.+?)-->", RegexOptions.Singleline);

            string? configJson = null;

            if (jsonMatch.Success)
            {
                configJson = jsonMatch.Groups[1].Value;
            }

            if (string.IsNullOrEmpty(configJson))
            {
                throw new InvalidOperationException(
                    "This PDF does not contain embedded report configuration data. " +
                    "Only PDFs generated by this application can be imported.");
            }

            // Deserialize the JSON back to config object
            var config = JsonSerializer.Deserialize<MobileAppReportConfig>(configJson);

            if (config == null)
            {
                throw new InvalidOperationException("Failed to deserialize report configuration from PDF metadata.");
            }

            // Don't automatically map - let the user choose via the import dialog
            return config;
        }
        catch (Exception ex) when (ex is not InvalidOperationException)
        {
            throw new InvalidOperationException(
                $"Unable to read PDF file. The file may be corrupted or incompatible. Error: {ex.Message}", ex);
        }
    }
}
